on:
  release:
    types: [published]

permissions:
  contents: write

name: Publish binaries on release

jobs:
  build-and-package:
    name: Build and package binaries
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Build and upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
        with:
          bin: gritty
          include: README.md,CHANGELOG.md,LICENSE
          checksum: sha256
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
