on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

name: Create release and publish binaries

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          excludeTypes: "chore,build,docs,other,style,ci"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          make_latest: false
          body: ${{ steps.changelog.outputs.changes }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "chore(main): release ${{ github.ref_name }}"
          file_pattern: CHANGELOG.md

  build-and-package:
    name: Build and package binaries
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        env:
          NAME: gritty
          TARGET: ${{ matrix.target }}
        run: .github/scripts/package.sh

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          make_latest: true
          files: "gritty*"
