name: Rust
on:
  push:
    branches: [ "main" ]
    paths:
    - ".github/workflows/rust.yml"
    - "src/**"
    - "tests/**"
    - "examples/**"
    - "gritty-clap/**"
    - "Cargo.toml"
    - "Cargo.lock"

  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run sccache
      uses: mozilla-actions/sccache-action@v0.0.5
    - name: Build
      run: cargo build --verbose
      env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
    - name: Run tests
      run: cargo test --verbose
      env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
